In [ ]:
#numpy array and basic
import numpy as np


In [9]:
#creating numpy arrays 
import numpy as np 
#1D Array 
arr_1d=np.array([10,20,30]) 
print("numpy 1d array:",arr_1d)

#2D array 
arr_2d=np.array([[10,20,30], [40,50,60]]) 
print("numpy 2d array:\n",arr_2d)

numpy 1d array: [10 20 30]
numpy 2d array:
 [[10 20 30]
 [40 50 60]]


Arrays:
An array is defined as a collection of items that are stored in contiguous memory locations
* it is a container which can hold a fixed no of items and these items should be the same type
* A combination of arrays a lot of time.thye array can reduce the overall size of the code

Difference between numpy and list

Example

Python List:
marks = [10, 20, 30, 40]
print(marks)

//For adding 5 to every value, you normally need a loop:
marks = [10, 20, 30, 40]
result = [x + 5 for x in marks]
print(result)

//NumPy Array:

import numpy as np
marks = np.array([10, 20, 30, 40])
result = marks + 5
print(result)

Output:

[15 25 35 45]


In [11]:
import time as t
#list
start=t.time()
list_op=[i*2 for i in range(10000)]
print("List operation time:",t.time()-start)

#array
start=t.time()
arr_op=np.arange(10000)*2
print("Array operation time:",t.time()-start)

List operation time: 0.0029535293579101562
Array operation time: 0.00966024398803711


creating array from scratch

In [17]:
import numpy as np
#Zeros
zeros=np.zeros([2,3])
print("Zeros array\n",zeros)
#Ones
ones=np.ones([2,3])
print("ones array\n",ones)
#Full
full=np.full((2,3),7)
print("full array\n",full)
#random
random=np.random.random((2,2))
print("random array\n",random)
#Sequence
sequence = np.arange(1, 11)
print("Sequence\n", sequence)

Zeros array
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array
 [[1. 1. 1.]
 [1. 1. 1.]]
full array
 [[7 7 7]
 [7 7 7]]
random array
 [[0.83594859 0.8255085 ]
 [0.58795935 0.25590087]]
Sequence
 [ 1  2  3  4  5  6  7  8  9 10]


vector,matrix and tensor

In [5]:
import numpy as np
vector=np.array([1,2,3,4,5])
print("vector:",vector)

matrix=np.array([[1,2,3],
                [4,5,6]])
print("Matrix:\n",matrix)

tensor=np.array([[1,2],
                 [2,3],
                 [3,4]])
print("Tensor:\n",tensor)

vector: [1 2 3 4 5]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[1 2]
 [2 3]
 [3 4]]


Array properties

In [6]:
print(f"Vector: {vector}\nShape: {vector.shape}\nDimensions: {vector.ndim}\nSize: {vector.size}\nData Type: {vector.dtype}")
print(f"Matrix:\n{matrix}\nShape: {matrix.shape}\nDimensions: {matrix.ndim}\nSize: {matrix.size}\nData Type: {matrix.dtype}")
print(f"Tensor:\n{tensor}\nShape: {tensor.shape}\nDimensions: {tensor.ndim}\nSize: {tensor.size}\nData Type: {tensor.dtype}")

Vector: [1 2 3 4 5]
Shape: (5,)
Dimensions: 1
Size: 5
Data Type: int32
Matrix:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int32
Tensor:
[[1 2]
 [2 3]
 [3 4]]
Shape: (3, 2)
Dimensions: 2
Size: 6
Data Type: int32


Array resphaping

In [14]:
import numpy as np
arr_id=np.arange(12)
print("Original arr:",arr_id)
reshape=arr_id.reshape((3,4))
print("Reshaped:\n",reshape)

arr_2d=np.array(([1,2,3],
                [5,6,7]))
flatten=arr_2d.flatten()
print("Flattered:\n",flatten)

Original arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattered:
 [1 2 3 5 6 7]
