NUMPY ARRAY OPERATIONS

In [6]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70])
print("Basic slicing:",arr[4:7])
print("slicing with step:",arr[1:6:2])
print("negative indexing:",arr[-1])

Basic slicing: [50 60 70]
slicing with step: [20 40 60]
negative indexing: 70


In [11]:
import  numpy as np
#                id,2023,2024,2025
sales=np.array([[0,10000,22000,33000],#biryani
               [1,32000,14000,23000],#pizza
               [2,20000,30000,40000],#IceCream
                ])
print("in 2025 sales of pizza:",sales[1,3])
print("all sales of biryani:",sales[0,1:])
print("print all slaes of 2025",sales[:,3])
print("Pizza and IceCream last two years:",sales[1:,2:])

in 2025 sales of pizza: 23000
all sales of biryani: [10000 22000 33000]
print all slaes of 2025 [33000 23000 40000]
Pizza and IceCream last two years: [[14000 23000]
 [30000 40000]]


Sorting

In [13]:
import numpy as np
arr=np.array([1,4,5,3,2,7,6,8,9])
print("Sorting arr:",np.sort(arr))
print("Sorting arrb with dType:",sorted(arr))


Sorting arr: [1 2 3 4 5 6 7 8 9]
Sorting arrb with dType: [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
import numpy as np
arr_2d=np.array([[1,2],
                [2,3],
                [3,4]])
print("Sorting 2d:\n",arr_2d)

Sorting 2d:
 [[1 2]
 [2 3]
 [3 4]]


In [17]:
import numpy as np

arr_2d = np.array([[1, 9],
                   [8, 5],
                   [10, 2]])

# Row-wise sorting
print("Row-wise sorting:\n", np.sort(arr_2d, axis=1))

# Column-wise sorting
print("Column-wise sorting:\n", np.sort(arr_2d, axis=0))

Row-wise sorting:
 [[ 1  9]
 [ 5  8]
 [ 2 10]]
Column-wise sorting:
 [[ 1  2]
 [ 8  5]
 [10  9]]


FILTER

In [19]:
nums=np.array([4,3,2,9,6,5,8])
even_nums=nums[nums%2==0]
print("Even Numbers:",even_nums)

#filter with marks
cgpa=np.array([4,4.5,5.6,6.7,8.9,9])
res=cgpa>7
print(res)

Even Numbers: [4 2 6 8]
[False False False False  True  True]


FANCY INDEXING

In [27]:
import numpy as np
#year  2021   2022  2023  2024 2025
sales=np.array([20000,30000,40000,50000,60000])
odd_year_sales=[0,2,4]
print("Odd year sales",sales[odd_year_sales])

Odd year sales [20000 40000 60000]


how to use where in numpy???

In [28]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(np.where(arr > 25))

(array([2, 3, 4], dtype=int64),)


Adding

In [29]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))
print("Combined array:", result)

Combined array: [1 2 3 4 5 6]


In [32]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11,10]])

compatible = arr1.shape[1] == arr2.shape[1]

print("Compatibility:", compatible)

Compatibility: True
